coding style fixed, minor fixes, introduced some error management
git-svn-id: http://192.168.2.3/yaffmap/svn/trunk/update_agents/luci@158 5eed78a2-3918-4851-bc8f-e53b4248f697

diff --git a/files/etc/init.d/yaffmap b/files/etc/init.d/yaffmap
--- a/files/etc/init.d/yaffmap
+++ b/files/etc/init.d/yaffmap
@@ -20,19 +20,38 @@ do
 done
 
 
-upload_error(){
-	local returnstring="$1"
+upload(){
+	[ "$DEBUG" = "1" ] &&	echo "entered upload()"
 	
+	local error=0 returnstring errorcode errormessage error=0 txurl
+  
+	rem_trailing_comma
+	if [ -n "$1" ]
+	then
+		txurl="$1"
+	else
+		txurl="$URL$UPLOADPREFIX$DATA$UPLOADSUFFIX"
+	fi
+
+	if [ "$PRETEND_UPLOAD" = "1" ]
+	then
+		echo "This would have been transmitted without '-p':"
+		echo "$txurl"
+	else
+		returnstring="$( wget -T30 -q -O- $txurl )"
+		error=$?
+	fi
+
 	errorcode=$( echo $returnstring | cut -d"|" -f1 )
 	errormessage=$( echo $returnstring | cut -d"|" -f2 )
-	returndata=$( echo $returnstring | cut -d"|" -f3 )
+	SERVER_RESPONSE=$( echo $returnstring | cut -d"|" -f3 )
 
 	if [ "$DEBUG" = "1" ]
 	then
-		length=${#TXURL}
+		length=${#txurl}
 		echo "\$TXURL is $length long"
-		echo "upload-string: $TXURL"
-		echo "update returnstring: $returnstring"
+		echo "upload-string: $txurl"
+		echo "update returnstring: $SERVER_RESPONSE"
 	fi
 
 	if [ ! "$errorcode" = "0" ] 
@@ -43,55 +62,59 @@ upload_error(){
 		echo 
 		echo "Error Text: $errormessage"
 		echo 
-		echo "Transmit String: $TXURL"
+		echo "Transmit String: $txurl"
 		echo
-		UPLOAD_SUCCESSFUL=0
-	fi
-}
-
-upload(){
-	[ "$DEBUG" = "1" ] &&	echo "entered upload()"
-  
-	rem_trailing_comma
-	if [ -n "$1" ]
-	then
-		TXURL="$1"
-	else
-		TXURL="$URL$UPLOADPREFIX$DATA$UPLOADSUFFIX"
-	fi
-
-	if [ "$PRETEND_UPLOAD" = "1" ]
-	then
-		echo "This would have been transmitted without '-p':"
-		echo "$TXURL"
-	else
-		upload_error "$( wget -T30 -q -O- $TXURL )"
+		error=1
 	fi
 
 	DATA=""
-	TXURL=""
+	
+	[ "$DEBUG" = "1" ] && echo "exiting upload() $error"
+	return $error
 }
 
 upload_split_check(){
+#	[ "$DEBUG" = "1" ] && echo "entering upload_split_check()"
+	local error=0
+	
 	length=${#DATA}
 	if [ $length -gt 1500 ]
 	then
 		upload
+		error=$?
 		DATA=""
 	fi
+	
+	if [ "$UPLOADSPLITCHECKERROR" -eq 1 ] 
+	then
+		error=1
+	fi
+	UPLOADSPLITCHECKERROR=$error
+	
+#	[ "$DEBUG" = "1" ] && echo "exiting upload_split_check() $error"
+	return $error
 }
 
 rp_links(){
+	local error=0
+	
 	obj neighbour
 		for rp in $ROUTINGPROTOCOLS
 		do
-			${rp}_links
+			if ! ${rp}_links; then error=1; fi
 		done
 	endobj
+
+	upload
+	[ $error -eq 0 ] && error=$?
+
+	[ "$DEBUG" = "1" ] && echo "exiting rp_links() $error"	
+	return $error
 }
 
 
 getid(){
+	local error=0
 	eval $( ip addr | awk '
 	{
 		if($0~/ether/){
@@ -108,17 +131,23 @@ getid(){
 
 	[ "$GETIDIP" = "1" ] && ip_addon="&ipv4Addr=$ip"
 	
-	upload "$URL?do=getID&macAddr=$macaddr$ip_addon"
-
-	eval "$returndata"
-
-	saveid "$id"
+	if upload "$URL?do=getID&macAddr=$macaddr$ip_addon"
+	then
+		eval "$SERVER_RESPONSE"
+		saveid "$id"
+	else
+		error=1
+	fi
+	
+	[ "$DEBUG" = "1" ] && echo "exiting getid() $error"
+	return $error
 }
 
 
 update(){
 	[ "$DEBUG" = "1" ] &&	echo "entered update() $1"
-	update_mode="$1"
+	
+	local update_mode="$1" error=0
 
 	load_node_data
 	if [ "$id" = "0" -o -z "$id" ] 
@@ -137,12 +166,11 @@ update(){
 	
 	case $update_mode in
 		link)
-			rp_links
-			upload
-			rf_links
-			upload
+			if ! rp_links; then error=1; fi
+			if ! rf_links; then error=1; fi
 			;;
-		global)	olsr_global_update
+		global)	
+			if ! olsr_global_update ; then error=1; ERROR_REASON="$ERROR_REASON global_map_update"; fi
 			;;
 		* )	
 			load_node_data	
@@ -152,37 +180,19 @@ update(){
 			attr hostname $( uname -n )
 			[ -n "$lat" ] && attr latitude $lat
 			[ -n "$lon" ] && attr longitude $lon
-			upload
+			if ! upload; then error=1; ERROR_REASON="$ERROR_REASON node_data"; fi
 		
-			network_interfaces
-			upload
-
-			rp_links
-			upload
-
-			rf_links
-			upload
+			if ! network_interfaces; then error=1; ERROR_REASON="$ERROR_REASON interface_data"; fi
+			if ! rp_links; then error=1; ERROR_REASON="$ERROR_REASON rplink_data"; fi
+			if ! rf_links; then error=1; ERROR_REASON="$ERROR_REASON rflink_data"; fi
 			;;
 	esac
 
-	[ "$UPLOAD_SUCCESSFUL" = "1" ] && 
-		[ "$QUIET" = "0" ] && 
-			[ "$PRETEND_UPLOAD" = "0" ] && 
-				echo "Update successful. Server reported no errors."
+	[ "$DEBUG" = "1" ] && echo "exiting update() $error"
+	return $error
 }
 
-
-start(){
-	create_config
-	add_to_cron		
-}
-
-stop (){
-	grep -v yaffmap /etc/crontabs/root > /tmp/yaffmap.tmp
-	mv /tmp/yaffmap.tmp /etc/crontabs/root
-}
-
-
+local error=0 usage=0
 args=$@
 
 for s in $@
@@ -205,12 +215,23 @@ do
 done
 
 case $( echo $args | cut -d" " -f1 ) in
-	start|stop) $1
+	start)
+		if ! create_config; then error=1; fi
+		if ! add_to_cron; then error=1; fi
 		;;
-	update) update $2
+	stop)
+		grep -v yaffmap /etc/crontabs/root > /tmp/yaffmap.tmp
+		mv /tmp/yaffmap.tmp /etc/crontabs/root
 		;;
-	restart)	stop
-						start
+	update) 
+		update $2
+		error=$?
+		;;
+	restart)	
+		$0 stop
+		[ $? -eq 1 ] && error=1
+		$0 start
+		[ $? -eq 1 ] && error=1
 		;;
 	*)	
 			echo "usage: $0 [options] start|stop|update"
@@ -219,5 +240,18 @@ case $( echo $args | cut -d" " -f1 ) in
 			echo "	-q		do not show show success or error messages"
 			echo "	-p		data is printed on screen instead of being uploaded"
 			echo "	--getidip	use also IP address to retrieve nodeID from map server"
+			usage=1
+		;;
 esac
-	
+
+
+if [ $usage -eq 0 ]
+then
+	if [ $error -eq 0 ]
+	then
+		echo "Update Successful"
+	else
+		echo "Error during update. ERROR_REASON=$ERROR_REASON"
+		echo "Please start with argument -v and mail the output to the developers"
+	fi
+fi
diff --git a/files/lib/yaffmap/common_rp_olsr b/files/lib/yaffmap/common_rp_olsr
--- a/files/lib/yaffmap/common_rp_olsr
+++ b/files/lib/yaffmap/common_rp_olsr
@@ -2,8 +2,11 @@
 ROUTINGPROTOCOLS="$ROUTINGPROTOCOLS olsr"
 
 olsr_links_common(){
-	[ "$DEBUG" = "1" ] &&	echo "entered olsr_links()"
-	olsr_config=$1
+	[ "$DEBUG" = "1" ] &&	echo "entered olsr_links_common()"
+
+	local olsr_config=$1 error=0
+	local metric ipversion my_ip n_ip lq nlq etx
+	
 	obj olsr
 		attr metric $( grep LinkQualityAlgorithm $olsr_config | cut -d" " -f2 | sed 's/"//g' ) 
 		ipversion=$( grep IpVersion $olsr_config | cut -d" " -f2 )
@@ -19,27 +22,40 @@ EOM
 EOM
 					;;
 		esac
-	
-		array link        
-		while read my_ip n_ip lq nlq etx 
-		do
-			if [ -n "$n_ip" -a "$etx" != "INFINITE" ]; then
-				obj
-					attr sourceAddr $my_ip
-					attr destAddr $n_ip	
-					attr rx $lq
-					attr tx $nlq
-					attr cost $etx
-				endobj
-			fi
-		done 
-		endarr 
+		
+		if [ $? ]
+		then
+			array link        
+			while read my_ip n_ip lq nlq etx 
+			do
+				if [ -n "$n_ip" -a "$etx" != "INFINITE" ]; then
+					obj
+						attr sourceAddr $my_ip
+						attr destAddr $n_ip	
+						attr rx $lq
+						attr tx $nlq
+						attr cost $etx
+					endobj
+				fi
+			done 
+			endarr
+		else
+			error=1
+		fi
 	endobj
+		
+	[ "$DEBUG" = "1" ] && echo "exiting olsr_links_common() $error"
+	return $error
 }
 
 olsr_global_update_common(){
+	[ "$DEBUG" = "1" ] && echo "entered olsr_global_update_common() $1 $suffix"
 
-	updateintervalglobal=$1
+	local updateintervalglobal=$1
+	local suffix=$2
+	local UPLOADPREFIXLOCAL
+	local error=0
+
 
 	UPLOADPREFIXLOCAL="?do=globalUpdate"
 
@@ -51,14 +67,6 @@ olsr_global_update_common(){
 	endarr -v UPLOADSUFFIX
 	rem_trailing_comma -v UPLOADSUFFIX
 
-
-	get_dnssuffix(){
-		config_get suffix "$1" suffix
-	}
-	
-	config_load olsrd
-	config_foreach get_dnssuffix LoadPlugin
-	
 	cp /var/etc/hosts.olsr $TEMP_DIR
 	cp /var/run/latlon.js $TEMP_DIR
 	
@@ -134,6 +142,10 @@ EOM
 
 	eval "$( $TEMP_DIR/latlon_crawler.awk $TEMP_DIR/latlon.js )"
 	upload
+	[ $UPLOADSPLITCHECKERROR -eq 1 ] && error=1 || error=$?
 	rm $TEMP_DIR/latlon_crawler.awk $TEMP_DIR/latlon.js $TEMP_DIR/hosts.olsr
+	
+	[ "$DEBUG" = "1" ] && echo "exiting olsr_global_update_common() $error"
+	return $error
 }
 
diff --git a/files/lib/yaffmap/uci_common b/files/lib/yaffmap/uci_common
--- a/files/lib/yaffmap/uci_common
+++ b/files/lib/yaffmap/uci_common
@@ -11,6 +11,8 @@
 #
 
 config_get_batch(){
+	local s
+	
 	for s in $*
 	do
 		eval "config_get $s \"$1\" $s"
@@ -39,6 +41,7 @@ EOF
 }
 
 add_to_cron(){
+	local minutes nodeinterval linkinterval int s dez fract minstep
 	config_load freifunk_map
 	config_get_batch ffmap nodeinterval linkinterval
 	minutes=$(date | cut -d":" -f2)
@@ -111,6 +114,9 @@ EOF
 
 interface_addresses(){
 	[ "$DEBUG" = "1" ] &&	echo "entered interface_addresses() $1"
+
+	local ipaddr ip6addr ifname type aliasesmacaddr macaddr config a
+
 	ip_params(){		
 		local config=$1
 		config_get_batch "$config" ipaddr ip6addr
@@ -142,21 +148,20 @@ interface_addresses(){
 
 wifi_device_attributes(){
 	[ "$DEBUG" = "1" ] &&	echo "entered wifi_device_attributes() $1"
+
 	
 	wifi_iface_attributes(){
 		[ "$DEBUG" = "1" ] &&echo "entered wifi_iface_attributes() $1"
-		local config="$1"
+		local config="$1" device ssid bssid mode ifname wlmac network
 	
 		config_get device "$config" device
 		if [ "$device" = "$2" ]
 		then
-			config_get_batch "$config" ssid bssid mode ifname
+			config_get_batch "$config" ssid bssid mode ifname network
 			obj
 				[ -n "$ssid" ] && attr essid $ssid
 				[ -n "$bssid" ] && attr bssid $bssid
 				[ -n "$mode" ] && attr wlMode $mode
-				config_get network "$config" network
-				config_get ifname "$config" ifname
 				attr name $ifname
 				wlmac=$( ip addr show dev $ifname | grep -e '.*:.*:.*:.*:.*:.*' | cut -d" " -f 6 )
 				attr wlMacAddr $wlmac
@@ -167,7 +172,7 @@ wifi_device_attributes(){
 		fi
 	} 
 
-	local config="$1"
+	local config="$1" ignore type channel hwmode txpower macaddr antDirection antGain antBeamH antBeamV antPol antTilt macaddr var_cont s
 	
 	[ -z "$(uci get freifunk_map.$config.ignore 2>/dev/null )" ] && wifi_default_config	$config
 	
@@ -201,6 +206,7 @@ network_interfaces(){
 		local config=$1
 		local isbridge=0
 		local iswireless=0
+		local ignore ifname
 		
 		for net in $WIRELESS_NETWORKS
 		do
@@ -224,6 +230,7 @@ network_interfaces(){
 		fi
 	}
 	
+	local error=0
 
 	config_load network
 	scan_interfaces
@@ -246,6 +253,12 @@ network_interfaces(){
 			network_iface $int
 		done
 	endarr
+	
+	upload
+
+	error=$?
+	[ "$DEBUG" = "1" ] && echo "exiting network_interfaces() $error"
+	return $error
 }
 
 rf_links(){
@@ -254,7 +267,7 @@ rf_links(){
 	rflinks_wifi_iface(){
 		[ "$DEBUG" = "1" ] &&	echo "entered rflinks_wifi_iface() $1"
 
-		local config=$1
+		local config="$1" device ifname macaddr temp 
 		config_get device "$config" device
 		
 		if [ "$device" = "$2" ]
@@ -278,10 +291,12 @@ rf_links(){
 	rflinks_wifi_device(){
 		[ "$DEBUG" = "1" ] &&	echo "entered rflinks_wifi_device() $1"
 
-		local config=$1
+		local config=$1 type
 		config_get type "$config" type
 		config_foreach rflinks_wifi_iface wifi-iface "$config" $type
 	}
+	
+	local error=0
 	
 	DEVICES=""
 	array rfNeighbour
@@ -292,5 +307,11 @@ rf_links(){
 			rflinks_wifi_device $wd
 		done
 	endarr
+
+	upload
+	
+	error=$?
+	[ "$DEBUG" = "1" ] && echo "exiting rf_links() $error"
+	return $error
 }
 
diff --git a/files/lib/yaffmap/uci_rp_olsr b/files/lib/yaffmap/uci_rp_olsr
--- a/files/lib/yaffmap/uci_rp_olsr
+++ b/files/lib/yaffmap/uci_rp_olsr
@@ -1,13 +1,50 @@
+#!/bin/sh
 . /lib/yaffmap/common_rp_olsr
 
 olsr_links(){
+	[ "$DEBUG" = "1" ] && echo "entering olsr_links()"
+	local config error=0
+
 	for config in /var/etc/olsrd.conf /var/etc/olsrd-ipv6.conf
 	do
-		[ -e $config ] && olsr_links_common $config
+		if [ -e $config ]
+		then
+			if ! olsr_links_common $config ; then error=1; ERROR_REASON="$ERROR_REASON olsr_links_common"; fi
+		fi
 	done
+
+	[ "$DEBUG" = "1" ] && echo "exiting olsr_links() $error"
+	return $error
 }
 
 olsr_global_update(){
+	[ "$DEBUG" = "1" ] && echo "entering olsr_global_update()"
+	local suffix 
+	local updateintervalglobal
+
 	updateintervalglobal=$( uci get freifunk_map.ffmap.globalinterval )
-  olsr_global_update_common $updateintervalglobal
+
+	get_dnssuffix(){
+		config_get suffix "$1" suffix
+	}
+	
+	local error=0
+	
+	config_load olsrd
+	config_foreach get_dnssuffix LoadPlugin
+
+	if [ -z "$updateintervalglobal" ]
+	then
+		echo "No olsr global update without globalinterval"
+		error=1
+	else
+		if ! olsr_global_update_common $updateintervalglobal $suffix 
+		then 
+			error=1
+			ERROR_REASON="$ERROR_REASON olsr_global_update_common"
+		fi
+	fi
+
+	[ "$DEBUG" = "1" ] && echo "exiting olsr_global_update() "$error
+	return $error
 }
